
CREATE DATABASE BANCODOBRASIL;

USE BANCODOBRASIL;

CREATE TABLE BANCO (nome VARCHAR(20), codConta INT, codCartao INT, PRIMARY KEY (codConta, codCartao)
FOREIGN KEY (codConta) REFERENCES CONTA (codConta), FOREIGN KEY (codCartao) REFERENCES CARTAO (codCartao));

CREATE TABLE CONTA (codConta INT, saldo REAL, limiteCredito REAL, PRIMARY KEY (codConta));

/* Saque, Deposito, Emprestimo */

CREATE TABLE CONTACORRENTE ();

CREATE TABLE CARTAO (codCartao INT);

CREATE TABLE CLIENTE (nome VARCHAR(30));

CREATE TABLE PFISICA (CPF INT);

CREATE TABLE PJURIDICA (CNPJ INT);

CREATE TABLE ENDERECO (logadouro VARCHAR(30), numero INT, bairro VARCHAR(30));

CREATE TABLE AUTORIZACAOCARTAO;